platform :ios, '15.0'

target 'RemoteDesktop' do
  use_frameworks!

  pod 'FirebaseAuth',     '~> 11.0'
  pod 'FirebaseDatabase', '~> 11.0'
  pod 'WebRTC-SDK',       '~> 114.5735'

  target 'RemoteDesktopTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
